version: '3.4'

services:
  landing:
    image: landing
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8090:8090
