export const confirmPayInitialData = {
  fa_IR: {
    '1': {
      label: 'شماره موبایل رو وارد کنید ',
      apiSubtitle: '',
      placeholder: '',
      name: 'phoneNumber',
      startAdornment: '+98',
      value: '',
      error: '',
      footnote: {
        type: 'subtitle',
        '1': 'نام کاربری، شماره موبایل شما خواهد بود و برای دریافت برنامه باید با یکی از این موارد، وارد',
        '2': 'بشید.',
        bottom: '',
      },
      button: 'تایید',
    },
    '2': {
      label: 'کد تایید را وارد کنید',
      apiSubtitle: '',
      placeholder: '',
      name: 'verifyCode',
      startAdornment: '',
      requestVerify: false,
      value: '',
      error: '',
      footnote: {
        type: 'timer',
        '1': 'درخواست مجدد ارسال کد',
        '2': '120',
        bottom: 'ویرایش شماره موبایل',
      },
      button: 'مشاهده برنامه',
    },
    isLoading: false,
  },
  en_US: {
    '1': {
      label: 'شماره موبایل رو وارد کنید ',
      apiSubtitle: '',
      placeholder: '',
      name: 'phoneNumber',
      startAdornment: '+98',
      value: '',
      error: '',
      footnote: {
        type: 'subtitle',
        '1': 'نام کاربری، شماره موبایل شما خواهد بود و برای دریافت برنامه باید با یکی از این موارد، وارد',
        '2': 'بشید',
        bottom: '',
      },
      button: 'دریافت کد تایید',
    },
    '2': {
      label: 'کد تایید را وارد کنید',
      apiSubtitle: '',
      placeholder: '',
      name: 'verifyCode',
      startAdornment: '',
      value: '',
      error: '',
      footnote: {
        type: 'timer',
        '1': 'درخواست مجدد ارسال کد',
        '2': '120',
        bottom: '',
      },
      button: 'مشاهده برنامه',
    },
    isLoading: false,
  },
};
